### ISSUE TITLE
error message in the logs

### ISSUE THREAD

**Issue by nicolas-cyfix** [bbenzikry/sqlalchemy-neo4j#3]
FYI, when I use your example, I got some error message in the logs

To remove it I found 2 solutions

```
    jpype.startJVM()

    import jpype.imports
    from java.lang import System
 System.setProperty("log4j2.loggerContextFactory","com.simba.neo4j.shaded.apache.logging.log4j.simple.SimpleLoggerContextFactory")
```

and to remove the info logs

```
    jpype.startJVM()

    import jpype.imports
    from java.lang import System
    System.setProperty("log4j2.loggerContextFactory","com.simba.neo4j.shaded.apache.logging.log4j.simple.SimpleLoggerContextFactory")

    from java.util.logging import LogManager
    LogManager.getLogManager().reset()
```

**Comment by bbenzikry** [comment]
Hi, can you add what error you're seeing so I have a reference? 
What JDBC driver version are you using? The latest one? 

As this is dependent on the JDBC driver itself, and is not a part of the python wrapper ( this project ), I don't really see it as relevant. 
I won't close this issue for now as the error itself may need to be handled.

**Comment by nicolas-cyfix** [comment]
Hello,
yes I am using the latest driver (I think 1.0.10?).
Anyway, it is not a "bug", it was more a FYI ;-)
And I was just starting your basic_use.py example:
```
# ./use.sh 
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
...
```

**Comment by bbenzikry** [comment]
Alright, thanks for letting me know for future reference.
I'll be closing this in the meantime.
